name: tscore
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - biopython
  - freesasa
  - pytorch::pytorch=2.4.1
  - pytorch::pytorch-cuda=12.1

# Create or update:
#   conda env create -f environment.yml || conda env update -n tscore -f environment.yml --prune
#   conda activate tscore
#   pip install torch-scatter torch-sparse torch-cluster torch-spline-conv \
#     -f https://data.pyg.org/whl/torch-2.4.1+cu121.html
#   pip install torch-geometric pytest
#   pip install -e .
